### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jawinn** [wjthomas9/duplicate-lines#5]
I just installed via Package Manager in Sublime Text 2, and restarted Sublime Text. Duplicate line is working as it was previously (select in middle of first line, and all of second line, and it only duplicates partial of the first line). Any idea why? I did not have it installed before.

Windows, Sublime Text 2.0.2 (licensed)

**Comment by wjthomas9** [comment]
Hi Jawinn, I never heard reports of anyone else having issues and I wasn't able to test on Windows. I'm going to close this, but please let me know if you still have issues.

**Comment by ricab** [comment]
I have a very similar issue, but on sublime 3, build 3176 currently. It worked on the first attempt, then never worked again. Tried removing and installing again multiple times, but no luck.

**Comment by ricab** [comment]
OK, got it: this was an issue with key bindings. _Fixed_ by adding a user key binding to replace the original behaviour:

```
  // The command below comes from the package with the same name.
  // It is different from the built-in "duplicate_line" (no s at the end).
  // The package's default key binding is different from the original.
  // The manual key binding hides the original to replace the behavior entirely.
  { "keys": ["ctrl+shift+d"], "command": "duplicate_lines" },
```
